UNIMPORTANT_FILE	=	delete_this

all:
	touch $(UNIMPORTANT_FILE)

# This will say that clean is already up to date
clean:
	$(RM) $(UNIMPORTANT_FILE)

# Fix by uncommenting below:
# .PHONY: clean all

# You can also have multiple PHONY per makefile
.PHONY: last-rule
last-rule:
	echo Ignore this one.
