# First rule in the file is always the first one to be executed.
first-rule:
	echo "Hey, this is the first rule in the file, but this isn't the one I want to run!"

all:
	echo "This is the all rule, the one I'm looking for!"

# I would not recommend this approach, put the rule you want to run first at the top of your file.
# .DEFAULT_GOAL := all
