name: Slides builder

on:
  push:
    branches:
      - main
    paths:
      - "slides"
      - ".github/workflows/slides-builder.yml"
      - "slides-builder/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  slides-builder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install nix
        uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6

      - name: Launch slides-builder
        shell: "bash -c \"cd slides-builder && nix develop -c bash -e {0}\""
        run: |
          make run-build

      - uses: actions/checkout@v6
        with:
          repository: https://codeberg.org/hugoarnal/website
          path: website
          ref: talks  # Temporary

      - name: Publish static files
        run: |
          ./scripts/publish-static-files slides-builder/build website
