name: Slides builder

on:
  push:
    branches:
      - main
    paths:
      - "slides"
      - ".github/workflows/slides-builder.yml"
      - "slides-builder/**"
      - "scripts/publish-static-files"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  slides-builder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install nix
        uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6

      - name: Launch slides-builder
        shell: "bash -c \"cd slides-builder && nix develop -c bash -e {0}\""
        run: |
          make run-build

      - name: Install SSH key
        uses: shimataro/ssh-key-action@87a8f067114a8ce263df83e9ed5c849953548bc3 # v2.8.1
        with:
          key: "${{ secrets.SSH_KEY }}"
          name: id_rsa
          # Manually add the Codeberg key
          known_hosts: |
            codeberg.org ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8hZi7K1/2E2uBX8gwPRJAHvRAob+3Sn+y2hxiEhN0buv1igjYFTgFO2qQD8vLfU/HT/P/rqvEeTvaDfY1y/vcvQ8+YuUYyTwE2UaVU5aJv89y6PEZBYycaJCPdGIfZlLMmjilh/Sk8IWSEK6dQr+g686lu5cSWrFW60ixWpHpEVB26eRWin3lKYWSQGMwwKv4LwmW3ouqqs4Z4vsqRFqXJ/eCi3yhpT+nOjljXvZKiYTpYajqUC48IHAxTWugrKe1vXWOPxVXXMQEPsaIRc2hpK+v1LmfB7GnEGvF1UAKnEZbUuiD9PBEeD5a1MZQIzcoPWCrTxipEpuXQ5Tni4mN

      - name: Clone website repo
        run: |
          git clone git@codeberg.org:hugoarnal/website.git website
          cd website

      - name: Publish static files
        # If the script errors out, it means there's probably nothing to update
        run: |
          ./scripts/publish-static-files slides-builder/build website || exit 0
